apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: core-harbor.entigo.io/demo/example-api:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: api
        - secretRef:
            name: api
        ports:
        - containerPort: 3001
